### ISSUE TITLE
Infinite recursion trying to evaluate that a type from `syn` is `Send`.

### ISSUE THREAD

**Issue by neon64** [dtolnay/syn#201]
(firstly, I understand you're probably not meant to stick bits of the AST in a global variable, but it worked in the current release (0.11.11) so I was doing it anyway)

Since switching to the master branch, it errors. I'm fairly sure the recursion is infinite because adding `#![recursion_limit="2048"]` won't fix it.

```rust
error[E0275]: overflow evaluating the requirement `*const (): std::marker::Send`
  --> derive_component/src/lib.rs:39:1
   |
39 | / lazy_static! {
40 | |     static ref CONTEXT2: Mutex<Context> = Mutex::new(Context::new());
41 | | }
   | |_^
   |
   = help: consider adding a `#![recursion_limit="128"]` attribute to your crate
   = note: required because it appears within the type `std::marker::PhantomData<*const ()>`
   = note: required because it appears within the type `proc_macro2::imp::Term`
   = note: required because it appears within the type `quote::__rt::Term`
   = note: required because it appears within the type `syn::Ident`
   = note: required because it appears within the type `syn::PatIdent`
   = note: required because it appears within the type `syn::Pat`
   = note: required because it appears within the type `(syn::Pat, std::option::Option<syn::tokens::Comma>)`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(syn::Pat, std::option::Option<syn::tokens::Comma>)>`
   = note: required because it appears within the type `alloc::raw_vec::RawVec<(syn::Pat, std::option::Option<syn::tokens::Comma>)>`
   = note: required because it appears within the type `std::vec::Vec<(syn::Pat, std::option::Option<syn::tokens::Comma>)>`
   = note: required because it appears within the type `syn::delimited::Delimited<syn::Pat, syn::tokens::Comma>`
   = note: required because it appears within the type `syn::PatTuple`
   = note: required because it appears within the type `syn::Pat`
   = note: required because it appears within the type `syn::ArgCaptured`
   = note: required because it appears within the type `syn::FnArg`
   = note: required because it appears within the type `(syn::FnArg, std::option::Option<syn::tokens::Comma>)`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(syn::FnArg, std::option::Option<syn::tokens::Comma>)>`
   = note: required because it appears within the type `alloc::raw_vec::RawVec<(syn::FnArg, std::option::Option<syn::tokens::Comma>)>`
   = note: required because it appears within the type `std::vec::Vec<(syn::FnArg, std::option::Option<syn::tokens::Comma>)>`
   = note: required because it appears within the type `syn::delimited::Delimited<syn::FnArg, syn::tokens::Comma>`
   = note: required because it appears within the type `syn::FnDecl`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<syn::FnDecl>`
   = note: required because it appears within the type `std::boxed::Box<syn::FnDecl>`
   = note: required because it appears within the type `syn::ExprClosure`
   = note: required because it appears within the type `syn::ExprKind`
   = note: required because it appears within the type `syn::Expr`
   = note: required because it appears within the type `syn::TyArray`
   = note: required because it appears within the type `syn::Ty`
   = note: required because it appears within the type `syn::MutTy`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<syn::MutTy>`
   = note: required because it appears within the type `std::boxed::Box<syn::MutTy>`
   = note: required because it appears within the type `syn::TyPtr`
   = note: required because it appears within the type `syn::Ty`
   = note: required because it appears within the type `(syn::Ty, std::option::Option<syn::tokens::Comma>)`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(syn::Ty, std::option::Option<syn::tokens::Comma>)>`
   = note: required because it appears within the type `alloc::raw_vec::RawVec<(syn::Ty, std::option::Option<syn::tokens::Comma>)>`
   = note: required because it appears within the type `std::vec::Vec<(syn::Ty, std::option::Option<syn::tokens::Comma>)>`
   = note: required because it appears within the type `syn::delimited::Delimited<syn::Ty, syn::tokens::Comma>`
   = note: required because it appears within the type `syn::TyTup`
   = note: required because it appears within the type `syn::Ty`
   = note: required because it appears within the type `syn::TypeBinding`
   = note: required because it appears within the type `(syn::TypeBinding, std::option::Option<syn::tokens::Comma>)`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(syn::TypeBinding, std::option::Option<syn::tokens::Comma>)>`
   = note: required because it appears within the type `alloc::raw_vec::RawVec<(syn::TypeBinding, std::option::Option<syn::tokens::Comma>)>`
   = note: required because it appears within the type `std::vec::Vec<(syn::TypeBinding, std::option::Option<syn::tokens::Comma>)>`
   = note: required because it appears within the type `syn::delimited::Delimited<syn::TypeBinding, syn::tokens::Comma>`
   = note: required because it appears within the type `syn::AngleBracketedParameterData`
   = note: required because it appears within the type `syn::PathParameters`
   = note: required because it appears within the type `syn::PathSegment`
   = note: required because it appears within the type `(syn::PathSegment, std::option::Option<syn::tokens::Colon2>)`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(syn::PathSegment, std::option::Option<syn::tokens::Colon2>)>`
   = note: required because it appears within the type `alloc::raw_vec::RawVec<(syn::PathSegment, std::option::Option<syn::tokens::Colon2>)>`
   = note: required because it appears within the type `std::vec::Vec<(syn::PathSegment, std::option::Option<syn::tokens::Colon2>)>`
   = note: required because it appears within the type `syn::delimited::Delimited<syn::PathSegment, syn::tokens::Colon2>`
   = note: required because it appears within the type `syn::Path`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<syn::Path>`
   = note: required because it appears within the type `std::boxed::Box<syn::Path>`
   = note: required because it appears within the type `syn::VisRestricted`
   = note: required because it appears within the type `syn::Visibility`
   = note: required because it appears within the type `syn::ItemStruct`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::collections::hash::table::RawTable<syn::Ident, syn::ItemStruct>`
   = note: required because it appears within the type `std::collections::HashMap<syn::Ident, syn::ItemStruct>`
   = note: required because it appears within the type `Context`
   = note: required because of the requirements on the impl of `std::marker::Sync` for `std::sync::Mutex<Context>`
   = note: required by `lazy_static::lazy::Lazy`
   = note: this error originates in a macro outside of the current crate
```

**Comment by mystor** [comment]
The overflow is a bit odd/unfortunate, but ast nodes in master syn are not Send or Sync, as identifiers are references into thread local string tables within proc-macro2.

**Comment by alexcrichton** [comment]
Indeed yeah, unfortunately these types are not intended to be sent across threads.

**Comment by Michael-F-Bryan** [comment]
I just encountered this as well. Are there any ways we can deal with this?

At the moment because negative trait bounds aren't stable my "workaround" (hack) is to add `unsafe impl Sync for Foo` for my types and just remember not to send them across threads. I tried adding a dummy non-Send type as the first field to short-circuit the trait resolution logic, but that doesn't seem to work.
