### ISSUE TITLE
Can't put syn::Ty in lazy_static

### ISSUE THREAD

**Issue by Arnavion** [dtolnay/syn#185]
I have some instances of `syn::Ty` in a `lazy_static` that works with syn v0.11.11. When updated to use syn's master branch (c1b76f51feee4d737eea59ff434ea775c2ebbf7f), it fails to compile with:

<details>
<summary>Toggle</summary>

```
error[E0275]: overflow evaluating the requirement `syn::delimited::Delimited<syn::FieldValue, syn::tokens::Comma>: std::marker::Sync`
   --> src\lib.rs:217:1
    |
217 | / lazy_static! {
218 | |         static ref TY_BOOL: ::syn::Ty = syn::parse("bool").unwrap();
219 | |         static ref TY_SEMVER_VERSION: ::syn::Ty = syn::parse("::semver::Version").unwrap();
220 | |         static ref TY_SEMVER_VERSIONREQ: ::syn::Ty = syn::parse("::semver::VersionReq").unwrap();
221 | |         static ref TY_STRING: ::syn::Ty = syn::parse("String").unwrap();
222 | |         static ref TY_U64: ::syn::Ty = syn::parse("u64").unwrap();
223 | | }
    | |_^
    |
    = help: consider adding a `#![recursion_limit="800"]` attribute to your crate
    = note: required because it appears within the type `syn::ExprStruct`
    = note: required because it appears within the type `syn::ExprKind`
    = note: required because it appears within the type `syn::Expr`
    = note: required because it appears within the type `syn::TyArray`
    = note: required because it appears within the type `syn::Ty`
    = note: required because it appears within the type `std::option::Option<syn::Ty>`
    = note: required because it appears within the type `syn::TyParam`
    = note: required because it appears within the type `(syn::TyParam, std::option::Option<syn::tokens::Comma>)`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<(syn::TyParam, std::option::Option<syn::tokens::Comma>)>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<(syn::TyParam, std::option::Option<syn::tokens::Comma>)>`
    = note: required because it appears within the type `std::vec::Vec<(syn::TyParam, std::option::Option<syn::tokens::Comma>)>`
    = note: required because it appears within the type `syn::delimited::Delimited<syn::TyParam, syn::tokens::Comma>`
    = note: required because it appears within the type `syn::Generics`
    = note: required because it appears within the type `syn::FnDecl`
    = note: required because it appears within the type `syn::MethodSig`
    = note: required because it appears within the type `syn::TraitItemMethod`
    = note: required because it appears within the type `syn::TraitItemKind`
    = note: required because it appears within the type `syn::TraitItem`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::TraitItem>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::TraitItem>`
    = note: required because it appears within the type `std::vec::Vec<syn::TraitItem>`
    = note: required because it appears within the type `syn::ItemTrait`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Item>`
    = note: required because it appears within the type `std::vec::Vec<syn::Item>`
    = note: required because it appears within the type `(syn::tokens::Brace, std::vec::Vec<syn::Item>)`
    = note: required because it appears within the type `std::option::Option<(syn::tokens::Brace, std::vec::Vec<syn::Item>)>`
    = note: required because it appears within the type `syn::ItemMod`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `std::boxed::Box<syn::Item>`
    = note: required because it appears within the type `syn::Stmt`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Stmt>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`
    = note: required because it appears within the type `std::vec::Vec<syn::Stmt>`
    = note: required because it appears within the type `syn::Block`
    = note: required because it appears within the type `syn::ImplItemMethod`
    = note: required because it appears within the type `syn::ImplItemKind`
    = note: required because it appears within the type `syn::ImplItem`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::ImplItem>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::ImplItem>`
    = note: required because it appears within the type `std::vec::Vec<syn::ImplItem>`
    = note: required because it appears within the type `syn::ItemImpl`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Item>`
    = note: required because it appears within the type `std::vec::Vec<syn::Item>`
    = note: required because it appears within the type `(syn::tokens::Brace, std::vec::Vec<syn::Item>)`
    = note: required because it appears within the type `std::option::Option<(syn::tokens::Brace, std::vec::Vec<syn::Item>)>`
    = note: required because it appears within the type `syn::ItemMod`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `std::boxed::Box<syn::Item>`
    = note: required because it appears within the type `syn::Stmt`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Stmt>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`
    = note: required because it appears within the type `std::vec::Vec<syn::Stmt>`
    = note: required because it appears within the type `syn::Block`
    = note: required because it appears within the type `syn::ImplItemMethod`
    = note: required because it appears within the type `syn::ImplItemKind`
    = note: required because it appears within the type `syn::ImplItem`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::ImplItem>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::ImplItem>`
    = note: required because it appears within the type `std::vec::Vec<syn::ImplItem>`
    = note: required because it appears within the type `syn::ItemImpl`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Item>`
    = note: required because it appears within the type `std::vec::Vec<syn::Item>`
    = note: required because it appears within the type `(syn::tokens::Brace, std::vec::Vec<syn::Item>)`
    = note: required because it appears within the type `std::option::Option<(syn::tokens::Brace, std::vec::Vec<syn::Item>)>`
    = note: required because it appears within the type `syn::ItemMod`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `std::boxed::Box<syn::Item>`
    = note: required because it appears within the type `syn::Stmt`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Stmt>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`
    = note: required because it appears within the type `std::vec::Vec<syn::Stmt>`
    = note: required because it appears within the type `syn::Block`
    = note: required because it appears within the type `syn::ImplItemMethod`
    = note: required because it appears within the type `syn::ImplItemKind`
    = note: required because it appears within the type `syn::ImplItem`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::ImplItem>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::ImplItem>`
    = note: required because it appears within the type `std::vec::Vec<syn::ImplItem>`
    = note: required because it appears within the type `syn::ItemImpl`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Item>`
    = note: required because it appears within the type `std::vec::Vec<syn::Item>`
    = note: required because it appears within the type `(syn::tokens::Brace, std::vec::Vec<syn::Item>)`
    = note: required because it appears within the type `std::option::Option<(syn::tokens::Brace, std::vec::Vec<syn::Item>)>`
    = note: required because it appears within the type `syn::ItemMod`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `std::boxed::Box<syn::Item>`
    = note: required because it appears within the type `syn::Stmt`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Stmt>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`
    = note: required because it appears within the type `std::vec::Vec<syn::Stmt>`
    = note: required because it appears within the type `syn::Block`
    = note: required because it appears within the type `syn::ImplItemMethod`
    = note: required because it appears within the type `syn::ImplItemKind`
    = note: required because it appears within the type `syn::ImplItem`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::ImplItem>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::ImplItem>`
    = note: required because it appears within the type `std::vec::Vec<syn::ImplItem>`
    = note: required because it appears within the type `syn::ItemImpl`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Item>`
    = note: required because it appears within the type `std::vec::Vec<syn::Item>`
    = note: required because it appears within the type `(syn::tokens::Brace, std::vec::Vec<syn::Item>)`
    = note: required because it appears within the type `std::option::Option<(syn::tokens::Brace, std::vec::Vec<syn::Item>)>`
    = note: required because it appears within the type `syn::ItemMod`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `std::boxed::Box<syn::Item>`
    = note: required because it appears within the type `syn::Stmt`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Stmt>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`
    = note: required because it appears within the type `std::vec::Vec<syn::Stmt>`
    = note: required because it appears within the type `syn::Block`
    = note: required because it appears within the type `syn::ImplItemMethod`
    = note: required because it appears within the type `syn::ImplItemKind`
    = note: required because it appears within the type `syn::ImplItem`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::ImplItem>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::ImplItem>`
    = note: required because it appears within the type `std::vec::Vec<syn::ImplItem>`
    = note: required because it appears within the type `syn::ItemImpl`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Item>`
    = note: required because it appears within the type `std::vec::Vec<syn::Item>`
    = note: required because it appears within the type `(syn::tokens::Brace, std::vec::Vec<syn::Item>)`
    = note: required because it appears within the type `std::option::Option<(syn::tokens::Brace, std::vec::Vec<syn::Item>)>`
    = note: required because it appears within the type `syn::ItemMod`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `std::boxed::Box<syn::Item>`
    = note: required because it appears within the type `syn::Stmt`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Stmt>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`
    = note: required because it appears within the type `std::vec::Vec<syn::Stmt>`
    = note: required because it appears within the type `syn::Block`
    = note: required because it appears within the type `syn::ImplItemMethod`
    = note: required because it appears within the type `syn::ImplItemKind`
    = note: required because it appears within the type `syn::ImplItem`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::ImplItem>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::ImplItem>`
    = note: required because it appears within the type `std::vec::Vec<syn::ImplItem>`
    = note: required because it appears within the type `syn::ItemImpl`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Item>`
    = note: required because it appears within the type `std::vec::Vec<syn::Item>`
    = note: required because it appears within the type `(syn::tokens::Brace, std::vec::Vec<syn::Item>)`
    = note: required because it appears within the type `std::option::Option<(syn::tokens::Brace, std::vec::Vec<syn::Item>)>`
    = note: required because it appears within the type `syn::ItemMod`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `std::boxed::Box<syn::Item>`
    = note: required because it appears within the type `syn::Stmt`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Stmt>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`
    = note: required because it appears within the type `std::vec::Vec<syn::Stmt>`
    = note: required because it appears within the type `syn::Block`
    = note: required because it appears within the type `syn::ImplItemMethod`
    = note: required because it appears within the type `syn::ImplItemKind`
    = note: required because it appears within the type `syn::ImplItem`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::ImplItem>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::ImplItem>`
    = note: required because it appears within the type `std::vec::Vec<syn::ImplItem>`
    = note: required because it appears within the type `syn::ItemImpl`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Item>`
    = note: required because it appears within the type `std::vec::Vec<syn::Item>`
    = note: required because it appears within the type `(syn::tokens::Brace, std::vec::Vec<syn::Item>)`
    = note: required because it appears within the type `std::option::Option<(syn::tokens::Brace, std::vec::Vec<syn::Item>)>`
    = note: required because it appears within the type `syn::ItemMod`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `std::boxed::Box<syn::Item>`
    = note: required because it appears within the type `syn::Stmt`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Stmt>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`
    = note: required because it appears within the type `std::vec::Vec<syn::Stmt>`
    = note: required because it appears within the type `syn::Block`
    = note: required because it appears within the type `syn::ImplItemMethod`
    = note: required because it appears within the type `syn::ImplItemKind`
    = note: required because it appears within the type `syn::ImplItem`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::ImplItem>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::ImplItem>`
    = note: required because it appears within the type `std::vec::Vec<syn::ImplItem>`
    = note: required because it appears within the type `syn::ItemImpl`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Item>`
    = note: required because it appears within the type `std::vec::Vec<syn::Item>`
    = note: required because it appears within the type `(syn::tokens::Brace, std::vec::Vec<syn::Item>)`
    = note: required because it appears within the type `std::option::Option<(syn::tokens::Brace, std::vec::Vec<syn::Item>)>`
    = note: required because it appears within the type `syn::ItemMod`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `std::boxed::Box<syn::Item>`
    = note: required because it appears within the type `syn::Stmt`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Stmt>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`
    = note: required because it appears within the type `std::vec::Vec<syn::Stmt>`
    = note: required because it appears within the type `syn::Block`
    = note: required because it appears within the type `syn::ImplItemMethod`
    = note: required because it appears within the type `syn::ImplItemKind`
    = note: required because it appears within the type `syn::ImplItem`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::ImplItem>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::ImplItem>`
    = note: required because it appears within the type `std::vec::Vec<syn::ImplItem>`
    = note: required because it appears within the type `syn::ItemImpl`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Item>`
    = note: required because it appears within the type `std::vec::Vec<syn::Item>`
    = note: required because it appears within the type `(syn::tokens::Brace, std::vec::Vec<syn::Item>)`
    = note: required because it appears within the type `std::option::Option<(syn::tokens::Brace, std::vec::Vec<syn::Item>)>`
    = note: required because it appears within the type `syn::ItemMod`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `std::boxed::Box<syn::Item>`
    = note: required because it appears within the type `syn::Stmt`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Stmt>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`
    = note: required because it appears within the type `std::vec::Vec<syn::Stmt>`
    = note: required because it appears within the type `syn::Block`
    = note: required because it appears within the type `syn::ImplItemMethod`
    = note: required because it appears within the type `syn::ImplItemKind`
    = note: required because it appears within the type `syn::ImplItem`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::ImplItem>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::ImplItem>`
    = note: required because it appears within the type `std::vec::Vec<syn::ImplItem>`
    = note: required because it appears within the type `syn::ItemImpl`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Item>`
    = note: required because it appears within the type `std::vec::Vec<syn::Item>`
    = note: required because it appears within the type `(syn::tokens::Brace, std::vec::Vec<syn::Item>)`
    = note: required because it appears within the type `std::option::Option<(syn::tokens::Brace, std::vec::Vec<syn::Item>)>`
    = note: required because it appears within the type `syn::ItemMod`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `std::boxed::Box<syn::Item>`
    = note: required because it appears within the type `syn::Stmt`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Stmt>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`
    = note: required because it appears within the type `std::vec::Vec<syn::Stmt>`
    = note: required because it appears within the type `syn::Block`
    = note: required because it appears within the type `syn::ImplItemMethod`
    = note: required because it appears within the type `syn::ImplItemKind`
    = note: required because it appears within the type `syn::ImplItem`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::ImplItem>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::ImplItem>`
    = note: required because it appears within the type `std::vec::Vec<syn::ImplItem>`
    = note: required because it appears within the type `syn::ItemImpl`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Item>`
    = note: required because it appears within the type `std::vec::Vec<syn::Item>`
    = note: required because it appears within the type `(syn::tokens::Brace, std::vec::Vec<syn::Item>)`
    = note: required because it appears within the type `std::option::Option<(syn::tokens::Brace, std::vec::Vec<syn::Item>)>`
    = note: required because it appears within the type `syn::ItemMod`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `std::boxed::Box<syn::Item>`
    = note: required because it appears within the type `syn::Stmt`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Stmt>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`
    = note: required because it appears within the type `std::vec::Vec<syn::Stmt>`
    = note: required because it appears within the type `syn::Block`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Block>`
    = note: required because it appears within the type `std::boxed::Box<syn::Block>`
    = note: required because it appears within the type `syn::ItemFn`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Item>`
    = note: required because it appears within the type `std::vec::Vec<syn::Item>`
    = note: required because it appears within the type `(syn::tokens::Brace, std::vec::Vec<syn::Item>)`
    = note: required because it appears within the type `std::option::Option<(syn::tokens::Brace, std::vec::Vec<syn::Item>)>`
    = note: required because it appears within the type `syn::ItemMod`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `std::boxed::Box<syn::Item>`
    = note: required because it appears within the type `syn::Stmt`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Stmt>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`
    = note: required because it appears within the type `std::vec::Vec<syn::Stmt>`
    = note: required because it appears within the type `syn::Block`
    = note: required because it appears within the type `syn::ImplItemMethod`
    = note: required because it appears within the type `syn::ImplItemKind`
    = note: required because it appears within the type `syn::ImplItem`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::ImplItem>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::ImplItem>`
    = note: required because it appears within the type `std::vec::Vec<syn::ImplItem>`
    = note: required because it appears within the type `syn::ItemImpl`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Item>`
    = note: required because it appears within the type `std::vec::Vec<syn::Item>`
    = note: required because it appears within the type `(syn::tokens::Brace, std::vec::Vec<syn::Item>)`
    = note: required because it appears within the type `std::option::Option<(syn::tokens::Brace, std::vec::Vec<syn::Item>)>`
    = note: required because it appears within the type `syn::ItemMod`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `std::boxed::Box<syn::Item>`
    = note: required because it appears within the type `syn::Stmt`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Stmt>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`
    = note: required because it appears within the type `std::vec::Vec<syn::Stmt>`
    = note: required because it appears within the type `syn::Block`
    = note: required because it appears within the type `syn::ImplItemMethod`
    = note: required because it appears within the type `syn::ImplItemKind`
    = note: required because it appears within the type `syn::ImplItem`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::ImplItem>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::ImplItem>`
    = note: required because it appears within the type `std::vec::Vec<syn::ImplItem>`
    = note: required because it appears within the type `syn::ItemImpl`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Item>`
    = note: required because it appears within the type `std::vec::Vec<syn::Item>`
    = note: required because it appears within the type `(syn::tokens::Brace, std::vec::Vec<syn::Item>)`
    = note: required because it appears within the type `std::option::Option<(syn::tokens::Brace, std::vec::Vec<syn::Item>)>`
    = note: required because it appears within the type `syn::ItemMod`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `std::boxed::Box<syn::Item>`
    = note: required because it appears within the type `syn::Stmt`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Stmt>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`
    = note: required because it appears within the type `std::vec::Vec<syn::Stmt>`
    = note: required because it appears within the type `syn::Block`
    = note: required because it appears within the type `syn::ExprIf`
    = note: required because it appears within the type `syn::ExprKind`
    = note: required because it appears within the type `syn::Expr`
    = note: required because it appears within the type `syn::FieldValue`
    = note: required because it appears within the type `(syn::FieldValue, std::option::Option<syn::tokens::Comma>)`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<(syn::FieldValue, std::option::Option<syn::tokens::Comma>)>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<(syn::FieldValue, std::option::Option<syn::tokens::Comma>)>`
    = note: required because it appears within the type `std::vec::Vec<(syn::FieldValue, std::option::Option<syn::tokens::Comma>)>`
    = note: required because it appears within the type `syn::delimited::Delimited<syn::FieldValue, syn::tokens::Comma>`
    = note: required because it appears within the type `syn::ExprStruct`
    = note: required because it appears within the type `syn::ExprKind`
    = note: required because it appears within the type `syn::Expr`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Expr>`
    = note: required because it appears within the type `std::boxed::Box<syn::Expr>`
    = note: required because it appears within the type `syn::ItemStatic`
    = note: required because it appears within the type `syn::ItemKind`
    = note: required because it appears within the type `syn::Item`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Item>`
    = note: required because it appears within the type `std::boxed::Box<syn::Item>`
    = note: required because it appears within the type `syn::Stmt`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syn::Stmt>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`
    = note: required because it appears within the type `std::vec::Vec<syn::Stmt>`
    = note: required because it appears within the type `syn::Block`
    = note: required because it appears within the type `syn::ExprIf`
    = note: required because it appears within the type `syn::ExprKind`
    = note: required because it appears within the type `syn::Expr`
    = note: required because it appears within the type `syn::TyArray`
    = note: required because it appears within the type `syn::Ty`
    = note: required by `lazy_static::lazy::Lazy`
    = note: this error originates in a macro outside of the current crate

error: aborting due to previous error
```
</details>

It happens with both stable `rustc 1.18.0 (03fc9d622 2017-06-06)` and nightly `rustc 1.20.0-nightly (9b85e1cfa 2017-07-07)`

**Comment by mystor** [comment]
AST nodes in the new version of syn aren't `Sync` anymore unfortunately. This is because unlike in syn v0.11, we now use `proc_macro`'s (or `proc_macro2`'s) `Term` (which represents a thread-local interned identifier), `TokenTree`, and other such types.

I don't think there is any good way to get around the fact that `proc_macro`'s interface is designed to generate non-threadsafe tokens, and thus our ASTs are not going to be threadsafe if we include them.

**Comment by Arnavion** [comment]
That makes sense.

I can just initialize them in the proc macro and pass them down. Don't strictly need them to be globals.

**Comment by Arnavion** [comment]
(Actually, since `Ty` no longer implements `Eq`, I don't have a reason to pre-create these `Ty`s anyway.)
