### ISSUE TITLE
Tests fail to compile with rustc 1.24.0-nightly (0077d128d 2017-12-14)

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#269]
```
error[E0308]: mismatched types
  --> tests/common/parse.rs:20:13
   |
20 |             "test_precedence".to_string(),
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `common::respan::syntax_pos::FileName`, found struct `std::string::String`
   |
   = note: expected type `common::respan::syntax_pos::FileName`
              found type `std::string::String`
help: try using a variant of the expected type
   |
20 |             common::respan::syntax_pos::FileName::Macros("test_precedence".to_string()),
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20 |             common::respan::syntax_pos::FileName::Custom("test_precedence".to_string()),
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by dtolnay** [comment]
Fixed in e959425c39eba3de72fd1dc135c86cfce7ddf678.
