### PR TITLE
Simplify dyn/impl parsing enabled by Punctuated improvements

### PR DESCRIPTION
**Pull request by dtolnay**
Cleanup of the code added in #1245. Enabled by #1247. This code is where I noticed #1246.

### CODE REVIEW

**Review by dtolnay — COMMENTED** [review]
Apparently this only works on Rust 1.40+, which we aren't requiring yet.

**Comment by dtolnay** [comment]
Older rustc:

```console
error[E0505]: cannot move out of `bounds` because it is borrowed
   --> src/ty.rs:930:59
    |
928 |   for bound in &bounds {
    |                -------
    |                |
    |                borrow of `bounds` occurs here
    |                a temporary with access to the borrow is created here ...
929 |       match bound {
930 |           TypeParamBound::Trait(_) => return Ok(bounds),
    |                                                 ^^^^^^ move out of `bounds` occurs here
...
935 |   }
    |   - ... and the borrow might be used here, when that temporary is dropped and runs the destructor for type `punctuated::Iter<'_, generics::TypeParamBound>`
```
